# Generated by Django 4.2.7 on 2025-04-12 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carrinho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_estimado', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='total estimado')),
                ('status', models.CharField(choices=[('em_progresso', 'Em Progresso'), ('finalizado', 'Finalizado')], default='em_progresso', max_length=50, verbose_name='status')),
                ('data_criacao', models.DateTimeField(auto_now_add=True, verbose_name='data de criação')),
            ],
            options={
                'verbose_name': 'carrinho',
                'verbose_name_plural': 'carrinhos',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_nutricional', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='score nutricional')),
                ('descricao', models.TextField(blank=True, verbose_name='descrição')),
            ],
            options={
                'verbose_name': 'match',
                'verbose_name_plural': 'matches',
            },
        ),
        migrations.CreateModel(
            name='ReceitaUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_selecao', models.DateTimeField(auto_now_add=True, verbose_name='data de seleção')),
                ('receita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.receita', verbose_name='receita')),
            ],
            options={
                'verbose_name': 'receita do usuário',
                'verbose_name_plural': 'receitas dos usuários',
            },
        ),
    ]
