# Generated by Django 4.2.7 on 2025-04-12 21:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('matches', '0001_initial'),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitausuario',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AddField(
            model_name='match',
            name='alimento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.alimento', verbose_name='alimento'),
        ),
        migrations.AddField(
            model_name='match',
            name='bebida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.bebida', verbose_name='bebida'),
        ),
        migrations.AddField(
            model_name='carrinho',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='usuário'),
        ),
        migrations.AlterUniqueTogether(
            name='receitausuario',
            unique_together={('usuario', 'receita')},
        ),
    ]
