# Generated by Django 4.2.7 on 2025-04-12 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alimento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('calorias', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='calorias')),
                ('proteinas', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='proteínas (g)')),
                ('carboidratos', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='carboidratos (g)')),
                ('gorduras', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='gorduras (g)')),
                ('preco_medio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço médio')),
            ],
            options={
                'verbose_name': 'alimento',
                'verbose_name_plural': 'alimentos',
            },
        ),
        migrations.CreateModel(
            name='Bebida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('calorias', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='calorias')),
                ('tipo', models.CharField(help_text='Ex: suco, chá, energético', max_length=50, verbose_name='tipo')),
                ('preco_medio', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='preço médio')),
            ],
            options={
                'verbose_name': 'bebida',
                'verbose_name_plural': 'bebidas',
            },
        ),
        migrations.CreateModel(
            name='Receita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('ingredientes', models.TextField(verbose_name='ingredientes')),
                ('tempo_preparo', models.IntegerField(verbose_name='tempo de preparo (min)')),
                ('calorias_totais', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='calorias totais')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='receitas/', verbose_name='imagem')),
            ],
            options={
                'verbose_name': 'receita',
                'verbose_name_plural': 'receitas',
            },
        ),
    ]
