# Generated by Django 4.2.7 on 2025-04-14 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receita',
            name='modo_preparo',
            field=models.TextField(blank=True, null=True, verbose_name='modo de preparo'),
        ),
        migrations.AddField(
            model_name='receita',
            name='porcoes',
            field=models.IntegerField(default=1, verbose_name='porções'),
        ),
    ]
