# Generated by Django 4.2.7 on 2025-06-23 01:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_receita_modo_preparo_receita_porcoes'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dieta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='nome')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='descrição')),
                ('data_inicio', models.DateField(verbose_name='data de início')),
                ('data_fim', models.DateField(blank=True, null=True, verbose_name='data de fim')),
                ('calorias_diarias', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='calorias diárias')),
                ('ativa', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'dieta',
                'verbose_name_plural': 'dietas',
                'ordering': ['-data_inicio'],
            },
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
        migrations.CreateModel(
            name='Refeicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('cafe_da_manha', 'Café da Manhã'), ('lanche_manha', 'Lanche da Manhã'), ('almoco', 'Almoço'), ('lanche_tarde', 'Lanche da Tarde'), ('jantar', 'Jantar'), ('ceia', 'Ceia')], max_length=20, verbose_name='tipo')),
                ('horario', models.TimeField(verbose_name='horário')),
                ('descricao', models.TextField(verbose_name='descrição')),
                ('calorias', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='calorias')),
                ('proteinas', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='proteínas (g)')),
                ('carboidratos', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='carboidratos (g)')),
                ('gorduras', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='gorduras (g)')),
                ('dieta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refeicoes', to='users.dieta')),
                ('receita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refeicoes', to='recipes.receita')),
            ],
            options={
                'verbose_name': 'refeição',
                'verbose_name_plural': 'refeições',
                'ordering': ['horario'],
            },
        ),
        migrations.CreateModel(
            name='MedidaCorporal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_registro', models.DateField(auto_now_add=True, verbose_name='data de registro')),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='peso (kg)')),
                ('altura', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='altura (cm)')),
                ('cintura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='cintura (cm)')),
                ('quadril', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='quadril (cm)')),
                ('braco_direito', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='braço direito (cm)')),
                ('braco_esquerdo', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='braço esquerdo (cm)')),
                ('coxa_direita', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='coxa direita (cm)')),
                ('coxa_esquerda', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='coxa esquerda (cm)')),
                ('panturrilha_direita', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='panturrilha direita (cm)')),
                ('panturrilha_esquerda', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='panturrilha esquerda (cm)')),
                ('pescoco', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='pescoço (cm)')),
                ('torax', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='tórax (cm)')),
                ('percentual_gordura', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='percentual de gordura (%)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas_corporais', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'usuário',
                'verbose_name_plural': 'usuários',
            },
        ),
        migrations.AddField(
            model_name='dieta',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dietas', to=settings.AUTH_USER_MODEL),
        ),
    ]
